//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorServerSideLocaliation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SfResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SfResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorServerSideLocaliation.Resources.SfResources", typeof(SfResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request Failed.
        /// </summary>
        public static string AutoComplete_ActionFailureTemplate {
            get {
                return ResourceManager.GetString("AutoComplete_ActionFailureTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        public static string AutoComplete_NoRecordsTemplate {
            get {
                return ResourceManager.GetString("AutoComplete_NoRecordsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Calendar_Today {
            get {
                return ResourceManager.GetString("Calendar_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request Failed.
        /// </summary>
        public static string ComboBox_ActionFailureTemplate {
            get {
                return ResourceManager.GetString("ComboBox_ActionFailureTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        public static string ComboBox_NoRecordsTemplate {
            get {
                return ResourceManager.GetString("ComboBox_NoRecordsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a date.
        /// </summary>
        public static string DatePicker_Placeholder {
            get {
                return ResourceManager.GetString("DatePicker_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DatePicker_Today {
            get {
                return ResourceManager.GetString("DatePicker_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string DateRangePicker_ApplyText {
            get {
                return ResourceManager.GetString("DateRangePicker_ApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DateRangePicker_CancelText {
            get {
                return ResourceManager.GetString("DateRangePicker_CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Range.
        /// </summary>
        public static string DateRangePicker_CustomRange {
            get {
                return ResourceManager.GetString("DateRangePicker_CustomRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string DateRangePicker_Days {
            get {
                return ResourceManager.GetString("DateRangePicker_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string DateRangePicker_EndLabel {
            get {
                return ResourceManager.GetString("DateRangePicker_EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a date range.
        /// </summary>
        public static string DateRangePicker_Placeholder {
            get {
                return ResourceManager.GetString("DateRangePicker_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Days.
        /// </summary>
        public static string DateRangePicker_SelectedDays {
            get {
                return ResourceManager.GetString("DateRangePicker_SelectedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string DateRangePicker_StartLabel {
            get {
                return ResourceManager.GetString("DateRangePicker_StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a date and time.
        /// </summary>
        public static string DateTimePicker_Placeholder {
            get {
                return ResourceManager.GetString("DateTimePicker_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DateTimePicker_Today {
            get {
                return ResourceManager.GetString("DateTimePicker_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request Failed.
        /// </summary>
        public static string DropDownList_ActionFailureTemplate {
            get {
                return ResourceManager.GetString("DropDownList_ActionFailureTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        public static string DropDownList_NoRecordsTemplate {
            get {
                return ResourceManager.GetString("DropDownList_NoRecordsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request Failed.
        /// </summary>
        public static string MultiSelect_ActionFailureTemplate {
            get {
                return ResourceManager.GetString("MultiSelect_ActionFailureTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        public static string MultiSelect_NoRecordsTemplate {
            get {
                return ResourceManager.GetString("MultiSelect_NoRecordsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +${count} more...
        /// </summary>
        public static string MultiSelect_OverflowCountTemplate {
            get {
                return ResourceManager.GetString("MultiSelect_OverflowCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string MultiSelect_SelectAllText {
            get {
                return ResourceManager.GetString("MultiSelect_SelectAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${count} selected.
        /// </summary>
        public static string MultiSelect_TotalCountTemplate {
            get {
                return ResourceManager.GetString("MultiSelect_TotalCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        public static string MultiSelect_UnSelectAllText {
            get {
                return ResourceManager.GetString("MultiSelect_UnSelectAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement value.
        /// </summary>
        public static string NumericTextBox_DecrementTitle {
            get {
                return ResourceManager.GetString("NumericTextBox_DecrementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment value.
        /// </summary>
        public static string NumericTextBox_IncrementTitle {
            get {
                return ResourceManager.GetString("NumericTextBox_IncrementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a time.
        /// </summary>
        public static string TimePicker_Placeholder {
            get {
                return ResourceManager.GetString("TimePicker_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Uploader_Abort {
            get {
                return ResourceManager.GetString("Uploader_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Uploader_Browse {
            get {
                return ResourceManager.GetString("Uploader_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Uploader_Cancel {
            get {
                return ResourceManager.GetString("Uploader_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Uploader_Clear {
            get {
                return ResourceManager.GetString("Uploader_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string Uploader_Delete {
            get {
                return ResourceManager.GetString("Uploader_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or drop files here.
        /// </summary>
        public static string Uploader_DropFilesHint {
            get {
                return ResourceManager.GetString("Uploader_DropFilesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload canceled.
        /// </summary>
        public static string Uploader_FileUploadCancel {
            get {
                return ResourceManager.GetString("Uploader_FileUploadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploader_InProgress {
            get {
                return ResourceManager.GetString("Uploader_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type is not allowed.
        /// </summary>
        public static string Uploader_InvalidFileType {
            get {
                return ResourceManager.GetString("Uploader_InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is too large.
        /// </summary>
        public static string Uploader_InvalidMaxFileSize {
            get {
                return ResourceManager.GetString("Uploader_InvalidMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is too small.
        /// </summary>
        public static string Uploader_invalidMinFileSize {
            get {
                return ResourceManager.GetString("Uploader_invalidMinFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Uploader_Pause {
            get {
                return ResourceManager.GetString("Uploader_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload paused.
        /// </summary>
        public static string Uploader_PauseUpload {
            get {
                return ResourceManager.GetString("Uploader_PauseUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to upload.
        /// </summary>
        public static string Uploader_ReadyToUploadMessage {
            get {
                return ResourceManager.GetString("Uploader_ReadyToUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Uploader_Remove {
            get {
                return ResourceManager.GetString("Uploader_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove file.
        /// </summary>
        public static string Uploader_RemovedFailedMessage {
            get {
                return ResourceManager.GetString("Uploader_RemovedFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File removed successfully.
        /// </summary>
        public static string Uploader_RemovedSuccessMessage {
            get {
                return ResourceManager.GetString("Uploader_RemovedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Uploader_Resume {
            get {
                return ResourceManager.GetString("Uploader_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Uploader_Retry {
            get {
                return ResourceManager.GetString("Uploader_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Uploader_Upload {
            get {
                return ResourceManager.GetString("Uploader_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File failed to upload.
        /// </summary>
        public static string Uploader_UploadFailedMessage {
            get {
                return ResourceManager.GetString("Uploader_UploadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully.
        /// </summary>
        public static string Uploader_UploadSuccessMessage {
            get {
                return ResourceManager.GetString("Uploader_UploadSuccessMessage", resourceCulture);
            }
        }
    }
}
